apiVersion: v1
kind: Service
metadata:
  name: lab7-service
spec:
  selector:
    app: lab7
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab7-deployment
spec:
  selector:
    matchLabels:
      app: lab7
  replicas: 3
  template:
    metadata:
      labels:
        app: lab7
    spec: 
      containers:
        - name: lab7
          image: boblouis14086020/lab7:latest
          ports:
          - containerPort: 80
